### ISSUE TITLE
How to trigger the command palette to appear?

### ISSUE THREAD

**Issue by tpayet** [traels-it/kommandant#18]
Hi! I just came across this gem and found it wonderful!

I installed your gem on a new rails project using Tailwindcss & Meilisearch. How do you display the command palette? What are the key bindings to toggle it?

**Comment by woller** [comment]
I completely forgot to document that. It does not come with any default keybindings, but instead uses the built in [keyboard event filter](https://stimulus.hotwired.dev/reference/actions#keyboardevent-filter) from Stimulus.
I've got it setup like this in our app:
```
<body class="min-h-full flex bg-zinc-100"
    data-controller="command-palette keyboard-navigation ahoy"
    data-action="keydown.meta+k->command-palette#toggle keydown.ctrl+k->command-palette#toggle keydown.esc->command-palette#hide keydown.down->keyboard-navigation#down keydown.up->keyboard-navigation#up keydown.enter->keyboard-navigation#select">
  ...
</body>
```

**Comment by woller** [comment]
I updated the documentation with some more details about this.
